# Auto-generated by PATCH-09
import pandas as pd
import numpy as np

def ema(s: pd.Series, n: int) -> pd.Series:
    return s.ewm(span=int(n), adjust=False).mean()

def rsi(close: pd.Series, n: int = 14) -> pd.Series:
    n = int(n)
    delta = close.diff()
    up = delta.clip(lower=0)
    down = (-delta).clip(lower=0)
    ru = up.ewm(alpha=1.0/n, adjust=False).mean()
    rd = down.ewm(alpha=1.0/n, adjust=False).mean()
    rs = ru / (rd.replace(0, np.nan))
    out = 100 - (100 / (1 + rs))
    return out.fillna(50)

def atr(high: pd.Series, low: pd.Series, close: pd.Series, n: int = 14) -> pd.Series:
    n = int(n)
    prev_close = close.shift(1)
    tr = pd.concat([
        (high - low).abs(),
        (high - prev_close).abs(),
        (low - prev_close).abs()
    ], axis=1).max(axis=1)
    return tr.ewm(alpha=1.0/n, adjust=False).mean()

def bbands(close: pd.Series, n: int = 20, k: float = 2.0):
    n = int(n); k = float(k)
    mid = close.rolling(n).mean()
    std = close.rolling(n).std(ddof=0)
    upper = mid + k*std
    lower = mid - k*std
    return upper, mid, lower

def macd(close: pd.Series, fast: int = 12, slow: int = 26, signal: int = 9):
    fast=int(fast); slow=int(slow); signal=int(signal)
    m = ema(close, fast) - ema(close, slow)
    s = ema(m, signal)
    h = m - s
    return m, s, h